name: ❓ Question
description: Ask a question about usage or functionality
title: "[QUESTION] "
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Have a question? We're here to help! Please provide as much detail as possible.

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: What would you like to know?
      placeholder: How do I...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What is your question about?
      options:
        - Installation and setup
        - Usage and commands
        - Error troubleshooting
        - Performance
        - Platform-specific (specify in question)
        - Feature understanding
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context (what you're trying to do, what you've tried, etc.)
      placeholder: |
        I'm trying to...
        I've already tried...
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Android/Termux
        - Other
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have read the README.md documentation
          required: true
        - label: I have searched existing issues and discussions
          required: true